config/routes.rb
Facturas::Application.routes.draw do
  
  get "facturacion/facturar"

  resources :facturas do
    resources :facturasproductos
  end
  resources :products
  resources :clients
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match "/printpdf", to: "facturacion#facturar"
  match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete

  root :to => 'facturas#index'

end

app/models/factura.rb
require 'num.rb'
class Factura < ActiveRecord::Base
  attr_accessible :client_id, :folio, :fecha, :m_pago, :total, :facturas_productos_attributes#:n_cliente, :m_pago, :folio, :fecha, :total
  
  
  has_many :facturas_productos, dependent: :destroy#, :foreign_key => "factura_id"#, :foreign_key => "folio"
  accepts_nested_attributes_for :facturas_productos, :reject_if => lambda { |a| a[:product_id].blank? }, :allow_destroy => true
  #has_many :products, :through => :facturasproductos
  
  
  belongs_to :client
  belongs_to :user
  
  validates :m_pago, :fecha, :folio, :presence => { :message => "no puede estar en blanco" }
  validates :folio, uniqueness: true

end

app/controllers/facturas_controller.rb
#encoding: utf-8
require 'num.rb'
class FacturasController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  # GET /facturas
  # GET /facturas.json
  def index
    @facturas = Factura.paginate(page: params[:page], :per_page => 10, :order => 'fecha DESC')

    respond_to do |format|
      format.html # index.html.erb
      
      format.json { render json: @facturas }
    end
  end

  # GET /facturas/1
  # GET /facturas/1.json
  def show
    @factura = Factura.find(params[:id])
    data = render_to_string( :action => :imprimir, :layout => false )
    File.open("/home/aggero/Desktop/factura.html", "w"){|f| f << data }
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @factura }
    end
  end

  # GET /facturas/new
  # GET /facturas/new.json
  def new
    @factura = Factura.new
    facturas_producto = @factura.facturas_productos.build 

  end


  # POST /facturas
  # POST /facturas.json
  def create
    @factura = Factura.new(params[:factura])
    @factura.activa = 1 
    @factura.fecha = Time.now

    respond_to do |format|
      if @factura.save
        format.html { redirect_to @factura, notice: 'La Factura fue creada satisfactoriamente.' }
        format.json { render json: @factura, status: :created, location: @factura }
      else
        format.html { render action: "new" }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /facturas/1
  # PUT /facturas/1.json
  def update
    @factura = Factura.find(params[:id])
    @factura.activa = 0
    respond_to do |format|
      if @factura.update_attributes(params[:factura])
        format.html { redirect_to facturas_path, notice: 'La factura fue cancelada.' }
        format.json { head :no_content }
      else
        format.html { render action: "index" }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def search
    if params[:factura_id].exists?
      u = Factura.where('id = ?', params[:factura_id]).first
    end
    puts u.path
  end
  
  private
  
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Por favor inicie sesión."
      end
    end  
end

app/helpers/facturas_helper.rb
module FacturasHelper
  def importe(cant, precio)
    tempo = cant * precio
  end
  
  def calcular_subtotal(st, temp)
    subtotal = st + temp
  end
  
  def subtotal
    @subtotal = self.subtotal
  end
  
  def calcular_iva(st)
    iva = st.to_f * 0.16
  end
  #SI LO QUE SE QUIERE ES RESTAR EL IVA AL SUBTOTAL, AGREGAR @ A LA VARIABLE IVA EN CALCULAR IVA Y TOTAL
  def total(sub, desc)
    @total = sub.to_f - desc.to_f + (sub.to_f * 0.16)
    if @total < 0
      @total = 0
    else @total
    end
  end
  
  def cantidad_en_letras(cant)
    c = cant.to_i
    sufijo = (cant.modulo(1)+0.01).to_s
    n = Numlet.new(c, sufijo)
    n.a_letra
  end
end

app/views/facturas/_facturas_producto_fields.html.erb
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
<script>
$(document).ready(function(){
$( "body" ).on('keyup.autocomplete', '.descripcion', function() {
	$( this ).autocomplete({
		// minLength: 3,
		source: '<%= products_path(:json) %>',
		focus: function(event, ui) {
			
			$(this).val(ui.item.descripcion);
			return false;
		},
	    select: function( event, ui ) {
	    	
	    	$(this).val(ui.item.descripcion);
	        var index = this.id.substring(5);
	        $("#pr_id_"+index).val(ui.item.product_id);
	        $("#pr_unit_"+index).val(ui.item.p_unit);
	        $("#u_med_"+index).val(ui.item.u_medida);
	        $("#cant_"+index).val(0);
	        updatesum(document.getElementById("cant_"+index));
	        return false;
	    }  
		}).data("uiAutocomplete")._renderItem = function(ul, item) {
				return $("<li></li>").data("item.autocomplete", item).append(
	      '<a>' + item.descripcion + '</a>').appendTo(ul);
	    };
  })
});
</script>
<script type="text/javascript">

function updatesum(c) {
	id = c.id.substring(5);
	cantidad = document.getElementById("cant_"+id).value;
	price_input = document.getElementById("pr_unit_"+id);
	price = parseFloat(price_input.value);
	var m = (cantidad * price);
	document.getElementById("imp_"+id).value = m;
	CalculateTotal(c.form);
}
function CalculateTotal(frm) {
	
    var order_total = 0
    var iva = 0
    var total = 0
    // Run through all the form fields
    for (var i=0; i < frm.elements.length; ++i) {
    	
        // Get the current field
        form_field = frm.elements[i]
        
        // Get the field's id
        form_name = form_field.id
        // Is it a "import" field?
        
        if (form_name.substring(0,4) == "imp_") {
            // Get the quantity
            importe_subt = parseInt(form_field.value)
            
            // Update the order total
            if (importe_subt >= 0) {
                order_total += importe_subt
                iva = (order_total * 0.16)
                total = iva + order_total
            }
        }
    }
    // Display the total rounded to two decimal places
    document.getElementById("valor_subtotal").value = "$" + round_decimals(order_total, 2)
    document.getElementById("valor_iva").value = "$" + round_decimals(iva, 2)
    document.getElementById("valor_total").value = "$" + round_decimals(total, 2)
}

function round_decimals(original_number, decimals) {
    var result1 = original_number * Math.pow(10, decimals)
    var result2 = Math.round(result1)
    var result3 = result2 / Math.pow(10, decimals)
    return pad_with_zeros(result3, decimals)
}

function pad_with_zeros(rounded_value, decimal_places) {
    // Convert the number to a string
    var value_string = rounded_value.toString()
    // Locate the decimal point
    var decimal_location = value_string.indexOf(".")
    // Is there a decimal point?
    if (decimal_location == -1) {
        // If no, then all decimal places will be padded with 0s
        decimal_part_length = 0
        // If decimal_places is greater than zero, tack on a decimal point
        value_string += decimal_places > 0 ? "." : ""
    }
    else {
        // If yes, then only the extra decimal places will be padded with 0s
        decimal_part_length = value_string.length - decimal_location - 1
    }
    // Calculate the number of decimal places that need to be padded with 0s
    var pad_total = decimal_places - decimal_part_length
    if (pad_total > 0) {
        // Pad the string with 0s
        for (var counter = 1; counter <= pad_total; counter++) 
            value_string += "0"
        }
    return value_string
}

function change_products_fields_ids(camp){
	identificador = camp.id;
	if (identificador == 'desc_1' || identificador == 'desc_2'  || identificador == 'desc_3'  || identificador == 'desc_4'  ||
		identificador == 'desc_5' || identificador == 'desc_6'  || identificador == 'desc_7'  || identificador == 'desc_8'  ||
		identificador == 'desc_9' || identificador == 'desc_10' || identificador == 'desc_11' || identificador == 'desc_12' ||
		identificador == 'desc_13'){ 
	}
	else {
		for (var i=1; i<14; i++){
			if (!document.getElementById("desc_"+i)){
				camp.id="desc_"+i;
				unidad_medida = document.getElementById("u_med");
				precio_unitario = document.getElementById("pr_unit");
				pr_id = document.getElementById("factura_facturas_productos_attributes_"+(i-1)+"_product_id");
				im = document.getElementById("factura_facturas_productos_attributes_"+(i-1)+"_importe");
				cantidad = document.getElementById("factura_facturas_productos_attributes_"+(i-1)+"_cant");
				unidad_medida.id = 'u_med_'+i;
				precio_unitario.id = 'pr_unit_'+i;
				pr_id.id = 'pr_id_'+i;
				im.id = 'imp_'+i;
				cantidad.id = "cant_"+i;
				document.getElementById("cant_"+i).readOnly = false;
				break;
			}
		}
	}
}
</script>
<div><%= f.text_field :product_id, :size => 5, :readonly => true %></div>
<div><%= f.text_field :cant, :size => 5, :onchange => 'updatesum(this)', :readonly => true %></div>
<div><input id="u_med" type="text" size="5" readonly="true" ></div>
<div><input id="desc" class="descripcion" type="text" size="5" onfocus="change_products_fields_ids(this)" ></div>
<div><input id="pr_unit" type="text" size="5" readonly="true"></div>
<div><%= f.text_field :importe, :size => 5, :readonly => true %></div>
</br>

app/views/facturas/_form.html.erb
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
<script>
$(document).ready(function(){
	$( "#nombre" ).autocomplete({
		// minLength: 3,
		source: '<%= clients_path(:json) %>',
		focus: function(event, ui) {
			
			$("#nombre").val(ui.item.nombre);
			return false;
		},
	    select: function( event, ui ) {
	    	
	    	$("#nombre").val(ui.item.nombre);
	        $("#id_client").val(ui.item.client_id);
	        $("#rfc").val(ui.item.RFC);
	        $("#dir").val(ui.item.direccion);
	        $("#edo").val(ui.item.estado);
	        $("#cd").val(ui.item.municipio);
	        $("#cp").val(ui.item.CP);
	        return false;
	    }
		}).data("uiAutocomplete")._renderItem = function(ul, item) {
				return $("<li></li>").data("item.autocomplete", item).append(
	      '<a>' + item.nombre + '</a>').appendTo(ul);
	    };
});
</script>
    <%= form_for(@factura) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
  		<div class="clientes_data">
	  		<legend>Ingrese los detalles del cliente</legend>
 				ID: <%= f.text_field :client_id, :size => 5, :id => "id_client" %>   RFC: <input type="text" id="rfc" size=5>     FOLIO <%= f.text_field :folio, :size => 5%><!-- Tel&eacute;fono: <input type="text" name="Tel">--><br />
				NOMBRE: <input type="text" id="nombre" size="70" ><br />
				DIRECCI&Oacute;N: <input type="text" id="dir" size="70" ><br />
				ESTADO: <input type="text" id="edo">   CIUDAD: <input type="text" id="cd">    C.P. <input type="text" id="cp" size = 7>
  		</div>
  		<div class="forma_pago">
  			<%= f.label :m_pago, "Forma de pago" %>
  			<%= f.select :m_pago, options_for_select([["Efectivo", "t"], ["Tarjeta bancaria", "s"], ["Transferencia bancaria", "b"]]) %>
  		</div>

  			<div class="tabla_prods">
  				<div class="titulos">
  					<div class="t1">CANT</div>
  					<div class="t2">SKU</div>
  					<div class="t3">UNIDAD DE MEDIDA</div>
  					<div class="t4">DESCRIPCI&Oacute;N</div>
  					<div class="t5">PRECIO</div>
  					<div class="t6">IMPORTE</div>
  				</div>
  				<div class="prods">
  				<%= f.fields_for :facturas_productos do |builder| %>
  					<%= render "facturas_producto_fields", :f => builder %>
  					<%= link_to_add_fields "Agregar producto", f, :facturas_productos %>
  				<% end %>
  				</div>
  			</div>
  			
  			
		<div id="observ" style="height:150px;width:300px;float:left;">
			<b>Observaciones</b><br>
			<div class="observ_text"><input type="text" style="height: 90px;width: 290px"/></div>
		</div>
		
		<div id="numeros" style="height:150px;width:400px;float:left;"><br />
			<div class="subtotal">
				<div class="titulo1"><b>Subtotal</b></div>
				<div class="valor1"><input type="text" id="valor_subtotal" size= "5" readonly="true"></div>
			</div>
			<div class="descuento">
				<div class="titulo2"><b>Descuento</b></div>
				<div class="valor2"><input type="text" id="desc" size= "5" readonly="true"></div>
			</div>
			<div class="iva">
				<div class="titulo3"><b>IVA</b></div>
				<div class="valor3"><input type="text" id="valor_iva" size= "5" readonly="true"></div>
			</div>
			<div class="total">
				<div class="titulo4"><b>Total</b></div>
				<div class="valor4"><%= f.text_field :total, :id => "valor_total", :readonly => true, :value => 0 %></div>
			</div>
		</div>
		<div id="botonpdf" style="clear:both;text-align:left;">
			<%= f.submit "Crear factura"%> &oacute; <%= link_to "Cancelar", facturas_path %>
		</div>

    <% end %>

app/views/facturas/imprimir.html.erb
<%= wicked_pdf_stylesheet_link_tag 'factura' %>
<div class="row">
  <div class="span6 offset3">
  	<% cliente= Client.find_by_client_id(current_factura.client_id) %>
  	<div class="cabecera">
	  	<div class="logo"><%= wicked_pdf_image_tag('clientes.png')%></div>
	  	<div class="datos_factura">
	  		<div class="titulo">FACTURA</div>
		  	<div class="title_num">N&uacute;mero:</div>
			<div class="campo_num">
					<%= @factura.folio %>
			</div>
	  		<div class="title_lyf">Lugar y fecha:</div>
	  		<div class="campo_lyf">
		  		<%= cliente.estado %>, <%= cliente.municipio %>, <%= @factura.fecha %>
	  		</div>
		  	<div class="title_f_pago">Forma de pago:</div>
	  		<div class="campo_f_pago">
		  		<%= @factura.m_pago %>
	  		</div>
	  	</div>
	</div>
  </div>
  	<div class="client">
	  		<div class="leyenda">Detalles del cliente</div>
	  		<div class="detalles_cliente">
				<div class="nombre_cliente"> NOMBRE: <%= cliente.nombre %></div>
				<div class="rfc_cliente"> RFC: <%= cliente.RFC %></div>
				<div class="dir_cliente"> DIRECCI&Oacute;N: <%= cliente.direccion %></div>
				<div class="ciudad_cliente"> CIUDAD: <%= cliente.municipio %></div>
				<div class="estado_cliente"> ESTADO: <%= cliente.estado %></div>
				<div class="cod_post"> C.P. <%= cliente.CP %></div>
			</div>
  	</div>
  	<div class="productos">
  			<div class="table">
  				<div class="columnas">
  					<div class="ncol_cant">CANTIDAD</div><div class="ncol_sku">SKU</div><div class="ncol_um">UNIDAD DE MEDIDA</div>
  					<div class="ncol_desc">DESCRIPCI&Oacute;N</div><div class="ncol_pre">PRECIO</div><div class="ncol_imp">IMPORTE</div>
  				</div>
  				<% st = 0 %>
  				<% contador = 1 %>
  				<% FacturasProducto.all.each do |fp| %>
  					<% if(fp.factura_id == @factura.factura_id) %>
  					<div class="campos">
  						<div class="col_cant">
  							<div id="cantidad_<%= contador %>" class="camp_cant"><%= fp.cant %></div>
  						</div>
  						<div class="col_sku">
  							<div id="sku_<%=contador %>" class="camp_sku"><%= Product.find_by_product_id(fp.product_id).sku%></div>
  						</div>
  						<div class="col_um">
  							<div id="um_<%= contador %>"class="camp_um"><%= Product.find_by_product_id(fp.product_id).u_medida %></div>
  						</div>
  						<div class="col_desc">
  							<div id="desc_<%= contador %>"class="camp_desc"><%= Product.find_by_product_id(fp.product_id).descripcion%></div>
  						</div>
  						<div class="col_precio">
  							<div id="precio_<%= contador %>"class="camp_prec"><%= number_to_currency(Product.find_by_product_id(fp.product_id).p_unit) %></div>
  						</div>
  						<div class="col_importe"><% imp= importe(fp.cant, Product.find_by_product_id(fp.product_id).p_unit) %>
  							<div id="importe_<%= contador %>"class="camp_imp"><%= number_to_currency(imp) %></div>
  						</div>
  					</div>
  						  <% st = calcular_subtotal(st, imp) %>
  						  <% contador = contador + 1 %>
  					<% end %>
  				<% end %>
  				<% iva = calcular_iva(st) %>
  				<% cantidad = total(st, 0) %>
  			</div>
  		</div>
  		<div class="bdd"<%= wicked_pdf_image_tag('clientes.png')%></div>
		<div class="observ">
			<div class="obs_label"><b>Observaciones</b><br></div>
			<div class="obs_campo"><%= @factura.observaciones %></div>
		</div>
		<div class="num_letra">
			<div class="num_letra_label"><b>Importe con letra</b><br></div>
			<div class="num_letra_campo"><%= cantidad_en_letras(cantidad) %></div>
		</div>
		<div class="firma_cliente">
			DEBO(MOS) Y PAGARE(MOS) INCONDICIONALMENTE A LA ORDEN DEL INEGI EL IMPORTE TOTAL
			QUE AMPARA ESTA FACTURA, RECONOCIENDO QUE DE NO SER LIQUIDADO DICHO IMPORTE EN
			LA FECHA PACTADA EN LA AUTORIZACI&Oacute;N DEL CR&Eacute;DITO, CAUSAR&Aacute; UN INTER&Eacute;S DEL 5%
			MENSUAL MAS I.V.A.<br /><br />
			FIRMA DEL CLIENTE O REPRESENTANTE LEGAL: ____________________________________________
		</div>
		<div class="numeros"><br />
			<div class="subtotal">
				<div class="titulo1">Subtotal</div>
				<div class="input1"><%= number_to_currency(st) %></div>
			</div>
			<div class="descuento">
				<div class="titulo2">Descuento</div>
				<div class="input2"> </div>
			</div>
			<div class="iva">
				<div class="titulo3">I.V.A.</div>
				<div class="input3"><%= number_to_currency(iva) %></div>
			</div>			
			<div class="total">
				<div class="titulo4">Total</div>
				<div class="input4"><%= number_to_currency(cantidad) %></div>
			</div>
		</div>
		<div class="vigencia">
			Comprobante impreso conforme con lo establecido en la fracci&oacute;n III del Art&iacute;culo 29-B del CFF y
			al &uacute;ltimo p&aacute;rrafo de la fracci&oacute;n I de la Regla I.2.8.3.1.1 de la RMF 2012.<br /><br />
			Este comprobante tendr&aacute; una vigencia de dos a&ntilde;os contados a partir de la fecha de aprobaci&oacute;n
			de la asignaci&oacute;n de folios.
		</div>
		<div class="advertencia">
			La reproducci&oacute;n ap&oacute;crifa de este comprobante constituye un delito en los t&eacute;rminos de las
			disposiciones fiscales.
  </div>
</div>

app/views/facturas/index.html.erb
<% provide(:title, 'Facturas recientes') %>

<table>
  <tr>
    <th>Folio</th>
    <th>Fecha</th>
    <th>Cliente</th>
    <th>Monto</th>
  </tr>

<% Factura.all.each do |factura| %></td>

		<% cliente = Client.find_by_client_id(factura.client_id) %>
		<td><% if(cliente.user_id == current_user.user_id) %></td>
		  <tr>
		  	<td><%= factura.folio %></td>
		  	<td><%= factura.fecha.strftime("%d/%m/%Y") %></td>
		  	<td><%= Client.find_by_client_id(factura.client_id).nombre %></td>
		  	<td><%= factura.total %></td>
		    <td><%= link_to 'Ver', factura %>&nbsp;|&nbsp;</td>
		    <% if factura.activa %>
		    <td><%= link_to 'Cancelar', factura, method: :put, data: { confirm: '¿Estas seguro que deseas cancelar ésta factura?' } %></td>
			<% else %>
			<td><%= "Cancelada" %></td>
		    <% end %>
		    
		  </tr>
		  <% end %>
<% end %>
</table>
<%= will_paginate @facturas %>

<br />

<%= link_to 'Nueva Factura', new_factura_path %>

app/views/facturas/new.html.erb
<% provide(:title, 'Nueva factura') %>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

app/views/facturas/show.html.erb
<% provide(:title, 'Mostrando factura') %>
<% establece_factura(@factura)%>

<div class="row">
  <div class="span6 offset3">
  		<fieldset>
	  		<legend>Detalles del cliente</legend>
	  		
				<% cliente= Client.find_by_client_id(current_factura.client_id) %>
				ID: <%= cliente.client_id %>   RFC: <%= cliente.RFC %><br />
				NOMBRE: <%= cliente.nombre %><br />
				DIRECCI&Oacute;N: <%= cliente.direccion %><br />
				ESTADO: <%= cliente.estado %>   CIUDAD: <%= cliente.municipio %>    C.P. <%= cliente.CP %>
  		</fieldset>
  		<fieldset>
  			M&eacute;todo de pago: <%= @factura.m_pago %>
  		</fieldset>
  		<fieldset>
  			<table>
  				<td>CANT</td><td>SKU</td><td>UNIDAD DE MEDIDA</td><td>DESCRIPCI&Oacute;N</td><td>PRECIO</td><td>IMPORTE</td><tr />
  				<% st, iva = 0 %>
  				<% FacturasProducto.all.each do |fp| %>
  					<% if(fp.factura_id == @factura.factura_id) %>
  						
  						<td><%= fp.cant %></td>
  						<td><%= Product.find_by_product_id(fp.product_id).sku%></td>
  						<td><%= Product.find_by_product_id(fp.product_id).u_medida %></td>
  						<td><%= Product.find_by_product_id(fp.product_id).descripcion%></td>
  						<td><%= number_to_currency(Product.find_by_product_id(fp.product_id).p_unit) %></td>
  						<% imp= importe(fp.cant, Product.find_by_product_id(fp.product_id).p_unit) %>
  						<td><%= number_to_currency(imp) %></td></tr>
  						  <% st = calcular_subtotal(st, imp) %>
  					<% end %>
  				<% end %>
  				<% iva = calcular_iva(st) %>
  				<% cantidad = total(st, 0) %>
  				
 </td>

  			</table>
  		</fieldset>
		<div id="observ" style="height:200px;width:300px;float:left;">
			<b>Observaciones</b><br>
			<input type="text" style="height: 50px;width: 290px"/>
			<b>Importe con letra:</b>
			<input type="text" style="height: 50px;width: 290px" value="<%= cantidad_en_letras(cantidad) %>" readonly="true"/>
		</div>
		
		<div id="numeros" style="height:200px;width:400px;float:left;"><br />
			<b>Subtotal</b><input type="text" size= "5" name="subt" value="<%= number_to_currency(st) %>" readonly="true"><br>
			<b>Descuento</b><input type="text" size= "5" name="descu" id="desc" readonly="true"><br>
			<b>I.V.A.</b><input type="text" size= "5" name="iva" value="<%= number_to_currency(iva) %>" readonly="true"><br>
			<b>Total</b><input type="text" size= "5" name="total" value="<%= number_to_currency(cantidad) %>" readonly="true"><br>
		</div>
		<div id="PDFPrinter" style="clear:both;text-align:left;">
			
			<%= link_to 'Imprimir en pdf', printpdf_path %> &oacute; <%= link_to "Regresar", facturas_path %>
		</div>
<div>
</div>    
  </div>
</div>