config/routes.rb
Facturas::Application.routes.draw do
  
  get "facturacion/facturar"

  resources :facturas do
    resources :facturasproductos
  end
  resources :products
  resources :clients
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match "/printpdf", to: "facturacion#facturar"
  match "/signup", to: "users#new"
  match "/signin", to: "sessions#new"
  match "/signout", to: "sessions#destroy", via: :delete

  root :to => 'facturas#index'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Proyecto", root_path, :id => "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home",      		root_path %></li>
					<% if signed_in? %>
					  <li><%= link_to "Usuarios", users_path %></li>
					  <li id="fat-menu" class="dropdown">
					  	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					  		Cuenta <b class="caret"></b>
					  	</a>
					  	<ul class="dropdown-menu">
					  		<li><%= link_to "Perfil", current_user %></li>
					  		<li><%= link_to "Opciones", edit_user_path(current_user) %></li>
					  		<li class="divider"></li>
					  		<li>
					  			<%= link_to "Cerrar sesión", signout_path, method: "delete" %>
					  		</li>
					  	</ul>
					  </li>
					  <% else %>
						<li><%= link_to "Inicio de sesión",   signin_path %></li>
					  <% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        
  		
		  <%= wicked_pdf_stylesheet_link_tag 'application' %>

  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
    	
        <title>New Web Project</title>
    </head>
    <body>
        <div class="header">
        	<div class="image">
        		<%= image_tag("logo_round.png") %>
        	</div>
        	<div class="account">
	          <% if signed_in? %>
        		<ul>
        			<li><%= current_user.empresa %></li>
        			<li><%= link_to "Mi cuenta", current_user %></li>
        			<li><%= link_to "Salir", signout_path, method: "delete" %></li>
        		</ul>
	          <% else %>
	            <li><%= link_to "Iniciar sesión", signin_path %></li>
	          <% end %>
        	</div>
        </div>
	      <% flash.each do |key, value| %>
	        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
	      <% end %>  
        <div class="main_panel">
        	<div class="menu">
        		<div class="element">
	        		<div class="bullet1"><%= image_tag("facturas.png") %></div>	
	        		<div class="text1"><%= link_to "Facturas",      facturas_path %></div>
        		</div>
        		<div class="element">
        			<div class="bullet2"><%= image_tag("clientes.png") %></div>
        			<div class="text2"><%= link_to "Clientes",      clients_path %></div>
        		</div>
        		<div class="element">
        			<div class="bullet3"><%= image_tag("productos.png") %></div>
        			<div class="text3"><%= link_to "Productos",      products_path %></div>
        		</div>
        		<div class="element">
        			<div class="bullet4"><%= image_tag("reportes.png") %></div>
        			<div class="text4">Reportes</div>
        		</div>
        	</div>
        	<div class="content_panel">
        		<div class="content_header">
        			<%= yield(:title) %>
        		</div>
        		<div class="content">
        			<%= yield %>
        		</div>
        	</div>
        </div>
    </body>
    
</html>